server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8

# hibernate는 SQL을 직접 사용하지않고 메서드만으로 쿼리를 사용하게 하는 라이브러리
# hibernate 기술을 쉽게 사용하게 해주는 라이브러리가 JPA이다.
# ddl-auto: create는 서버를 실행할 때 마다 테이블을 삭제하고 새로만드는 설정
# ddl-aute: none은 서버 실행할 떄 아무것도 하지 않는 설정
spring:
  mustache:
    expose-session-attributes: true
  datasource: 
      url: jdbc:mariadb://localhost:3306/greendb
      driver-class-name: org.mariadb.jdbc.Driver
      username: green
      password: green1234
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties: 
      hibernate.format_sql: true

  output:
    ansi:
      enabled: always    